sudo: required
services:
  - docker

language: c
compiler:
    - clang
    - gcc

env:
    matrix:
      - OS=el DIST=6 PACK=rpm
      - OS=el DIST=7 PACK=rpm
      - OS=fedora DIST=22 PACK=rpm
      - OS=fedora DIST=23 PACK=rpm
      - OS=fedora DIST=rawhide PACK=rpm
      - OS=ubuntu DIST=trusty PACK=deb
      - OS=ubuntu DIST=precise PACK=deb
      - OS=ubuntu DIST=wily PACK=deb
      - OS=ubuntu DIST=xenial PACK=deb
      - OS=debian DIST=jessie PACK=deb
      - OS=debian DIST=wheezy PACK=deb
      - OS=debian DIST=stretch PACK=deb
      - OS=debian DIST=sid PACK=deb
      - PACK=none

matrix:
    fast_finish: true
    allow_failures:
      - env: OS=el DIST=6 PACK=rpm
      - env: OS=el DIST=7 PACK=rpm
      - env: OS=fedora DIST=22 PACK=rpm
      - env: OS=fedora DIST=23 PACK=rpm
      - env: OS=fedora DIST=rawhide PACK=rpm
      - env: OS=ubuntu DIST=precise PACK=deb
      - env: OS=ubuntu DIST=trusty PACK=deb
      - env: OS=ubuntu DIST=wily PACK=deb
      - env: OS=ubuntu DIST=xenial PACK=deb
      - env: OS=debian DIST=jessie PACK=deb
      - env: OS=debian DIST=wheezy PACK=deb
      - env: OS=debian DIST=stretch PACK=deb
      - env: OS=debian DIST=sid PACK=deb
    exclude:
      - env: OS=el DIST=6 PACK=rpm
        compiler: clang
      - env: OS=el DIST=7 PACK=rpm
        compiler: clang
      - env: OS=fedora DIST=22 PACK=rpm
        compiler: clang
      - env: OS=fedora DIST=23 PACK=rpm
        compiler: clang
      - env: OS=fedora DIST=rawhide PACK=rpm
        compiler: clang
      - env: OS=ubuntu DIST=precise PACK=deb
        compiler: clang
      - env: OS=ubuntu DIST=trusty PACK=deb
        compiler: clang
      - env: OS=ubuntu DIST=wily PACK=deb
        compiler: clang
      - env: OS=ubuntu DIST=xenial PACK=deb
        compiler: clang
      - env: OS=debian DIST=wheezy PACK=deb
        compiler: clang
      - env: OS=debian DIST=jessie PACK=deb
        compiler: clang
      - env: OS=debian DIST=stretch PACK=deb
        compiler: clang
      - env: OS=debian DIST=sid PACK=deb
        compiler: clang

script:
  - git clone https://github.com/tarantool/build.git
  - bash build/pack/travis.sh

notifications:
  email: true
  irc: false
