// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// exportTarantoolConstants
void exportTarantoolConstants();
RcppExport SEXP tarantoolr_exportTarantoolConstants() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    exportTarantoolConstants();
    return R_NilValue;
END_RCPP
}
