// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// exportTarantoolConstants
void exportTarantoolConstants();
RcppExport SEXP _tarantoolr_exportTarantoolConstants() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    exportTarantoolConstants();
    return R_NilValue;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_Tarantool();

static const R_CallMethodDef CallEntries[] = {
    {"_tarantoolr_exportTarantoolConstants", (DL_FUNC) &_tarantoolr_exportTarantoolConstants, 0},
    {"_rcpp_module_boot_Tarantool", (DL_FUNC) &_rcpp_module_boot_Tarantool, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_tarantoolr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
